"""1. u1 = User.objects.create_user(username = '...')
   2. a1 = Author.objects.create(user = u1)
   3. cat1 = Category.objects.create(all_category = '...')
   4. p1 = Post.objects.create(author=a1, genre='...', title='...', content='...')
   5. PostCategory.objects.create(post=p1, category='...')
   6. com1 = Comment.objects.create(post=p1, user=u1, comment_text='...')
   7. p1.like(), com1.dislike()
   8. a1.update_rating()
   9. Author.objects.all().order_by('-rating').values('user', 'rating').first()
   10. Post.objects.all().order_by('-rating').values('time_create', 'author__user__username', 'rating','title').first()
       p1.preview()
   11. Comment.objects.filter(post=p1).values('time_comment', 'user__username', 'rating', 'comment_text')
   """